collections:
  rules:
    output: true
plugins:
  - jekyll-seo-tag
remote_theme: non-binary-trees/simple-srd-core
defaults:
  - scope:
      path: ""
      type: rules
    values:
      layout: default
