name: simple-srd
short_name: simple-srd
collections:
  docs:
    output: true
plugins:
  - jekyll-seo-tag
remote_theme: non-binary-trees/simple-srd-core
defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: default
